MPN-990: Fix test compilation error due to missing argument
[error] .../ttfi-core/src/test/scala/finals/SimplyTypedLambdaCalculusSpecs.scala:33: type mismatch;
[error]  found   : Int(2)
[error]  required: (Int => Int) => Int
[error]       eval(th4[Eval]) ==== 2
[error]                            ^
[error] one error found